### ISSUE TITLE
OMG, dude you need to try out relative line numbers, it makes so many things much easier in VIM 

### ISSUE THREAD

**Issue by judokasarin** [apicgg/dotfiles-public#1]
https://github.com/apicgg/dotfiles-public/blob/7681f52fb9fc495badc3d838886aa60ac5fc4e7b/nvim/lua/config/options.lua#L12

**Comment by apicgg** [comment]
> https://github.com/apicgg/dotfiles-public/blob/7681f52fb9fc495badc3d838886aa60ac5fc4e7b/nvim/lua/config/options.lua#L12

I am on it. 🫡
