### ISSUE TITLE
What is eza ? 

### ISSUE THREAD

**Issue by judokasarin** [apicgg/dotfiles-public#4]
https://github.com/apicgg/dotfiles-public/blob/f65c70b3e5a4abfbb395c1d0390f8b62f0b4cc8a/zshrc/.zshrc#L131C1-L131C15

**Comment by apicgg** [comment]
@judokasarin eza is replacement for `ls` in POSIX based system. Prettifies the output in the terminal for `ls`, `ls -la` etc.
![image](https://github.com/apicgg/dotfiles-public/assets/78271602/b4f84ea0-4533-4e3f-8ba3-558237072b72)
